[workspace]
authors = ["FilBalza <fbalzare@ucsc.edu>"]
channels = ["conda-forge"]
name = "erdos"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
qiskit = ">=2.2.1,<3"
qiskit_aer = "0.17.*"
pylatexenc = ">=2.10,<3"
